dubbo:
  application:
    name:  dubbo-consumer
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 3000

server:
  port: 8062

master:
  datasource:
    url: jdbc:mysql://localhost:3306/haotianbishe?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    userName: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
second:
  datasource:
    url: jdbc:mysql://localhost:3307/haotianbishe?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    userName: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false
    packages:
      trust-all: true
    pool:
      enabled: false
  redis:
    host: localhost
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    username: 2540097595@qq.com
    password: ybrykcdmzogpeahi
    default-encoding: utf-8
    port: 465
    from: 2540097595@qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
